// Generated by tauri-specta from src-tauri/src/commands.rs. Do not edit.
//
// `layout` and `report` are NOT here: they answer with an Arrow IPC
// ArrayBuffer, so call them as
//   invoke<ArrayBuffer>("layout", { generation, root, kind, viewport, minPx })
// and read the batch with apache-arrow's `tableFromIPC`. Their argument
// and error types below are generated and are the contract.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Starts a scan and returns immediately. Results arrive as events plus a
	 *  `scan_status` transition.
	 * 
	 *  # Errors
	 * 
	 *  [`StartError::AlreadyScanning`] (v1 runs exactly one),
	 *  [`StartError::RootNotFound`], [`StartError::RootNotADirectory`],
	 *  [`StartError::PermissionDenied`], or [`StartError::InvalidOptions`].
	 */
	scanStart: (root: string, options: ScanOptions) => typedError<ScanId, StartError>(__TAURI_INVOKE("scan_start", { root, options })),
	/**
	 *  Requests cancellation of `scan_id`.
	 * 
	 *  # Errors
	 * 
	 *  Never fails today; the signature keeps [`ScanError`](rdirstat_core::ScanError)
	 *  available for a supervisor that can report one.
	 */
	scanCancel: (scanId: ScanId) => typedError<CancelState, ScanError>(__TAURI_INVOKE("scan_cancel", { scanId })),
	/**
	 *  The `O(1)` state-machine answer for the launch screen and the status bar.
	 * 
	 *  # Errors
	 * 
	 *  Never fails; the umbrella type keeps the signature uniform.
	 */
	scanStatus: () => typedError<ScanStatus, CommandError>(__TAURI_INVOKE("scan_status")),
	/**
	 *  What the scan's recorded failures actually were.
	 * 
	 *  Answers from the **running** scan's live counters when one is active, and
	 *  from the published tree otherwise, so the same affordance works while the
	 *  error count is still climbing and after it has stopped. `limit` bounds the
	 *  sample list; the per-class counts are uncapped, and
	 *  [`ScanErrorReport::truncated`] says when there were more.
	 * 
	 *  # Errors
	 * 
	 *  Never fails. No scan and no published tree is an empty report, not an
	 *  error: "nothing has gone wrong yet" is an answer.
	 */
	scanErrors: (limit: number) => typedError<ScanErrorReport, CommandError>(__TAURI_INVOKE("scan_errors", { limit })),
	/**
	 *  One bounded page of children. `limit` is clamped to
	 *  [`MAX_CHILD_PAGE`](rdirstat_core::MAX_CHILD_PAGE).
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`],
	 *  [`QueryError::UnknownNode`], [`QueryError::VirtualGroup`], or
	 *  [`QueryError::InvalidCursor`].
	 */
	children: (generation: TreeGeneration, item: NodeId, sort: Sort, cursor: string | null, limit: number) => typedError<ChildPage, QueryError>(__TAURI_INVOKE("children", { generation, item, sort, cursor, limit })),
	/**
	 *  Details for one node, including one on-demand `lstat`.
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`],
	 *  [`QueryError::UnknownNode`], or [`QueryError::PathTooDeep`].
	 */
	nodeDetails: (generation: TreeGeneration, node: NodeId) => typedError<Details, QueryError>(__TAURI_INVOKE("node_details", { generation, node })),
	/**
	 *  The size-band histogram for a subtree.
	 * 
	 *  Always returns every band, including empty ones — "there is nothing over
	 *  50 GiB here" is an answer, and a table whose rows appear and vanish as the
	 *  user drills is harder to read than one that does not move.
	 * 
	 *  `O(subtree)`, which is why it runs on the blocking pool: the arena is already
	 *  in memory, but a whole-volume subtree is millions of nodes and that is not
	 *  work for the async executor.
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`], or
	 *  [`QueryError::UnknownNode`].
	 */
	sizeBands: (generation: TreeGeneration, node: NodeId) => typedError<SizeBandRow[], QueryError>(__TAURI_INVOKE("size_bands", { generation, node })),
	/**
	 *  The largest files inside one size band, for the breakdown accordion.
	 * 
	 *  A leaderboard, not an enumeration: the smallest band on a boot volume holds
	 *  ten million files, so `limit` is a hard ceiling and the caller already knows
	 *  the true count from `size_bands`.
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`], or
	 *  [`QueryError::UnknownNode`].
	 */
	sizeBandEntries: (generation: TreeGeneration, node: NodeId, band: number, limit: number) => typedError<SizeBandEntry[], QueryError>(__TAURI_INVOKE("size_band_entries", { generation, node, band, limit })),
	/**
	 *  The chain from the scan root down to a node, for the breadcrumb.
	 * 
	 *  Cheap — `O(depth)` with no `stat` — so the shell can call it on every
	 *  navigation instead of trying to remember where the user has been.
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`],
	 *  [`QueryError::UnknownNode`], or [`QueryError::PathTooDeep`].
	 */
	ancestors: (generation: TreeGeneration, node: NodeId) => typedError<Ancestor[], QueryError>(__TAURI_INVOKE("ancestors", { generation, node })),
	/**
	 *  The escaped full path of a node, for display and Copy Path only.
	 * 
	 *  # Errors
	 * 
	 *  [`QueryError::NoScan`], [`QueryError::StaleGeneration`],
	 *  [`QueryError::UnknownNode`], [`QueryError::VirtualGroup`], or
	 *  [`QueryError::PathTooDeep`].
	 */
	pathOf: (generation: TreeGeneration, item: NodeId) => typedError<DisplayPath, QueryError>(__TAURI_INVOKE("path_of", { generation, item })),
	/**
	 *  Mounted local volumes, for the launch screen.
	 * 
	 *  # Errors
	 * 
	 *  [`CommandError::Internal`] if the blocking task could not be joined.
	 */
	volumes: () => typedError<VolumeInfo[], CommandError>(__TAURI_INVOKE("volumes")),
	/**
	 *  What a Trash request would do, plus the token that authorizes it.
	 * 
	 *  # Errors
	 * 
	 *  [`ActionError::NoScan`] or [`ActionError::StaleGeneration`]. Per-item
	 *  problems are reported inside [`TrashPreview::rejected`], not as an error.
	 */
	trashPreview: (generation: TreeGeneration, nodes: NodeId[]) => typedError<TrashPreview, ActionError>(__TAURI_INVOKE("trash_preview", { generation, nodes })),
	/**
	 *  Moves a confirmed selection to the Trash through `NSFileManager`.
	 * 
	 *  # Errors
	 * 
	 *  [`ActionError::NoScan`], [`ActionError::StaleGeneration`], or
	 *  [`ActionError::InvalidConfirmation`]. Per-item failures are reported inside
	 *  [`TrashReport`], which is honest about partial success rather than
	 *  pretending the batch was atomic.
	 */
	moveToTrash: (generation: TreeGeneration, nodes: NodeId[], confirmation: ConfirmationToken) => typedError<TrashReport, ActionError>(__TAURI_INVOKE("move_to_trash", { generation, nodes, confirmation })),
	/**
	 *  Reveals a node in Finder.
	 * 
	 *  # Errors
	 * 
	 *  [`ActionError::NoScan`], [`ActionError::StaleGeneration`],
	 *  [`ActionError::NotActionable`] (the scan root or a virtual group),
	 *  [`ActionError::ChangedSinceScan`], or [`ActionError::OutsideScanRoot`].
	 */
	revealInFinder: (generation: TreeGeneration, node: NodeId) => typedError<null, ActionError>(__TAURI_INVOKE("reveal_in_finder", { generation, node })),
	/**
	 *  What a relocation would do, plus the token that authorizes it.
	 * 
	 *  Returns a plan even when the relocation cannot proceed: the reasons are the
	 *  point, and [`RelocatePlan::token`] is `None` for anything unactionable. The
	 *  frontend must key the confirm button on the token, not on the call
	 *  succeeding.
	 * 
	 *  # Errors
	 * 
	 *  [`RelocateError`] only for a request that cannot be described at all — an
	 *  unknown node, a path outside the scan root, or a destination that is not an
	 *  absolute, `..`-free path.
	 */
	relocatePlan: (generation: TreeGeneration, node: NodeId, destination: string, mode: RelocateMode, disposal: SourceDisposal) => typedError<RelocatePlan, RelocateError>(__TAURI_INVOKE("relocate_plan", { generation, node, destination, mode, disposal })),
	/**
	 *  Executes a planned relocation: copy, verify, dispose, symlink.
	 * 
	 *  **Long-running and blocking.** A multi-gigabyte subtree is copied and then
	 *  read back in full for verification, so this can run for minutes. It is on
	 *  `spawn_blocking` for that reason.
	 * 
	 *  # Errors
	 * 
	 *  [`RelocateError`]. Every failure before the disposal step leaves the source
	 *  untouched; [`RelocateError::SymlinkFailed`] is the sole exception and says
	 *  so in its message.
	 */
	relocateApply: (generation: TreeGeneration, node: NodeId, destination: string, mode: RelocateMode, disposal: SourceDisposal, confirmation: ConfirmationToken) => typedError<RelocateReport, RelocateError>(__TAURI_INVOKE("relocate_apply", { generation, node, destination, mode, disposal, confirmation })),
};

/** Events */
export const events = {
	scanProgress: makeEvent<ScanProgressEvent>("scan:progress"),
};

/* Constants */
export const BINARY_COMMANDS = ["layout","report"] as const;

export const LAYOUT_COLUMNS = ["node","depth","x","y","w","h","category"] as const;

export const LAYOUT_SCHEMA_VERSION = 1 as const;

export const MAX_CHILD_PAGE = 500 as const;

export const MIN_TILE_PX = 8.0 as const;

export const PROGRESS_MAX_HZ = 10 as const;

export const PROTOCOL_VERSION = 1 as const;

export const SCAN_PROGRESS_EVENT = "scan:progress" as const;

/* Types */
/**
 *  A Reveal or Trash action failed.
 * 
 *  Every variant that mentions identity exists because a path recorded at scan
 *  time is not authority at action time: the tree is a past observation and the
 *  filesystem has moved on.
 */
export type ActionError = 
/**  No completed scan is loaded. */
{ kind: "no_scan" } | 
/**  The request named a generation that is no longer current. */
{ kind: "stale_generation"; detail: {
	/**  What the caller asked for. */
	requested: TreeGeneration,
	/**  What is actually published. */
	current: TreeGeneration,
} } | 
/**  The id does not name a live node in this tree. */
{ kind: "unknown_node"; detail: {
	/**  The offending id. */
	node: NodeId,
} } | 
/**
 *  A virtual `<Files>` group, or the scan root, was selected. Neither can
 *  be revealed or trashed as a path.
 */
{ kind: "not_actionable"; detail: {
	/**  The offending id. */
	node: NodeId,
} } | 
/**
 *  The re-`stat` disagreed with the scan observation on device, inode, or
 *  kind. The item at that path is not the item the user selected.
 */
{ kind: "changed_since_scan"; detail: {
	/**  The reconstructed path. */
	path: DisplayPath,
} } | 
/**
 *  The reconstructed path resolved outside the scan root, e.g. through a
 *  component that became a symlink after the scan.
 */
{ kind: "outside_scan_root"; detail: {
	/**  The reconstructed path. */
	path: DisplayPath,
} } | 
/**
 *  The confirmation token is missing, expired, or bound to a different
 *  generation or selection. Trash never proceeds without a fresh one.
 */
{ kind: "invalid_confirmation" } | 
/**  macOS refused the operation. */
{ kind: "permission_denied"; detail: {
	/**  The path that was refused. */
	path: DisplayPath,
	/**  What was being attempted. */
	operation: Operation,
	/**  Raw `errno`. */
	os_code: number,
} } | 
/**  `NSFileManager.trashItem` failed for a reason of its own. */
{ kind: "trash_failed"; detail: {
	/**  The item that stayed put. */
	path: DisplayPath,
	/**  What Foundation reported. */
	reason: string,
} } | 
/**  Anything unexpected, already logged with its full source chain. */
{ kind: "internal"; detail: string };

/**
 *  One step on the path from the scan root down to a node.
 * 
 *  This is what the breadcrumb is built from. It carries the `NodeId` so a
 *  crumb is directly navigable, and the name so the frontend does not have to
 *  have visited the ancestor to be able to label it.
 */
export type Ancestor = {
	node: NodeId,
	/**  Basename. The root carries its full path instead — see [`ancestors`]. */
	name: DisplayPath,
	kind: Kind,
	logical: number,
	allocated: number,
};

/**
 *  A structural failure while building or loading an arena.
 * 
 *  These are bugs or corrupt inputs, not filesystem facts, which is why they
 *  are separate from [`ScanError`]. Loading a `*.rdstat` file turns every one
 *  of them into a closed failure before a single node reaches a command.
 */
export type ArenaError = 
/**
 *  The arena is full. The ceiling is
 *  [`MAX_NODE_INDEX`](crate::MAX_NODE_INDEX) because bit 31 is reserved for
 *  virtual groups.
 */
{ kind: "node_ceiling"; detail: {
	/**  The ceiling that was hit. */
	ceiling: number,
} } | 
/**  A single name exceeded the 16-bit length field. */
{ kind: "name_too_long"; detail: {
	/**  The offending length. */
	len: number,
} } | 
/**  The name blob grew past the 48-bit offset field. */
{ kind: "name_offset_overflow"; detail: {
	/**  The offending offset. */
	offset: number,
} } | 
/**
 *  A directory was pushed out of order, or is not a real arena slot. The
 *  sorted index would stop being searchable.
 */
{ kind: "dir_index_out_of_order"; detail: {
	/**  The offending id. */
	node: NodeId,
} } | 
/**  A link named a node that does not exist. */
{ kind: "unknown_node"; detail: {
	/**  The dangling id. */
	node: NodeId,
} } | 
/**
 *  A parent link chain did not terminate at the root within
 *  [`MAX_TREE_DEPTH`](crate::MAX_TREE_DEPTH) steps, i.e. the arena contains
 *  a cycle.
 */
{ kind: "cycle_or_depth"; detail: {
	/**  Where the walk started. */
	node: NodeId,
	/**  The depth ceiling. */
	limit: number,
} } | 
/**  A node was linked under a parent that is not a directory. */
{ kind: "not_a_directory"; detail: {
	/**  The offending parent. */
	parent: NodeId,
} };

/**  How far cancellation has progressed. */
export type CancelState = 
/**  The request was received. The UI acknowledges here, within 100 ms. */
"acknowledged" | 
/**
 *  Producers stopped, handles closed, queued batches dropped, and the
 *  builder discarded its partial state. Measured separately from the
 *  acknowledgement, because it depends on the kernel.
 */
"resources_closed" | 
/**  The scan had already finished; there was nothing to cancel. */
"already_finished" | 
/**  No scan with that [`ScanId`] is running. */
"not_found";

/**
 *  Identifier of one completed scan partition in the optional catalog.
 * 
 *  Distinct from [`ScanId`]: a `ScanId` is process-local and covers attempts, a
 *  `CatalogScanId` names a durable, reconciled Parquet partition.
 */
export type CatalogScanId = number;

/**
 *  Primary content category of a node, as assigned by `rdirstat-classify`.
 * 
 *  Defined here rather than in `rdirstat-classify` because
 *  [`Node`](crate::Node) stores it and `classify` depends on `core`, not the
 *  other way round. `rdirstat-classify` re-exports this type and must not
 *  define a second one.
 */
export type CategoryId = number;

/**  One bounded page of children. */
export type ChildPage = {
	/**
	 *  The tree these rows came from. The frontend rejects a page whose
	 *  generation is not the one it asked for.
	 */
	generation: TreeGeneration,
	/**  The parent that was paged. */
	parent: NodeId,
	/**  At most [`MAX_CHILD_PAGE`](crate::MAX_CHILD_PAGE) rows. */
	rows: ChildRow[],
	/**  Cursor for the next page, or `None` at the end. */
	next: Cursor | null,
	/**
	 *  Total children under `parent`, for the virtualizer's scrollbar. This is
	 *  one directory's fan-out, not a node count.
	 */
	total_children: number,
	/**  The effective limit after clamping. */
	limit: number,
};

/**
 *  One row in a child page.
 * 
 *  Carries the rendered name rather than a [`NameRef`](crate::NameRef): a
 *  frontend has no blob to resolve against.
 */
export type ChildRow = {
	/**  The node, or a tagged virtual `<Files>` group. */
	node: NodeId,
	/**  The escaped display name — this component only, not a path. */
	name: string,
	/**  Filesystem object kind. */
	kind: Kind,
	/**
	 *  Primary content category. The frontend resolves the colour from a CSS
	 *  variable; Rust never sends RGB.
	 */
	category: CategoryId,
	/**
	 *  Logical bytes: for a file its own size, for a directory its subtree
	 *  total.
	 */
	logical: number,
	/**  Allocated bytes, on the same basis. */
	allocated: number,
	/**  Modification time in Unix seconds. */
	mtime: number,
	/**
	 *  Bits from [`flags`](crate::flags). Drives the row annotations for
	 *  unreadable, excluded, aggregated, hard-linked, and sparse entries.
	 */
	flags: number,
	/**
	 *  Direct children, so the tree can render a disclosure triangle without a
	 *  second round trip. Zero for leaves and for virtual groups.
	 */
	children: number,
	/**
	 *  Whether this row is the synthesized `<Files>` group. Such a row cannot
	 *  be revealed, trashed, or expanded.
	 */
	is_virtual_group: boolean,
};

/**
 *  The umbrella error for a Tauri command that has no narrower type of its own.
 * 
 *  `src-tauri` converts `anyhow::Error` into this at the command boundary; the
 *  library crates never construct it. Every variant carries the protocol
 *  version so a frontend built against an older contract can say so instead of
 *  rendering a mystery.
 */
export type CommandError = 
/**  A scan could not be started. */
{ kind: "start"; detail: StartError } | 
/**  A query against a published tree failed. */
{ kind: "query"; detail: QueryError } | 
/**  A Reveal or Trash action failed. */
{ kind: "action"; detail: ActionError } | 
/**  A scan-level failure surfaced through a command. */
{ kind: "scan"; detail: ScanError } | 
/**  No completed scan is loaded. */
{ kind: "no_scan" } | 
/**  The frontend and backend disagree about the IPC contract version. */
{ kind: "protocol_mismatch"; detail: {
	/**  What the caller claimed. */
	requested: number,
	/**  What this build implements. */
	supported: number,
} } | 
/**  Anything unexpected, already logged with its full source chain. */
{ kind: "internal"; detail: string };

/**
 *  A hex-encoded configuration digest.
 * 
 *  Travels with every snapshot and Parquet partition so old category ids stay
 *  interpretable after the settings change that produced them.
 */
export type ConfigHash = string;

/**
 *  A confirmation token for a destructive action.
 * 
 *  Minted per selection and bound to the generation and the normalized node
 *  set, so a token cannot be replayed against a different tree or a selection
 *  the user did not see counted.
 */
export type ConfirmationToken = string;

/**
 *  An opaque paging cursor.
 * 
 *  Offset pagination is not used: at 500 rows a page and millions of children,
 *  an offset scan is quadratic and a concurrent generation swap makes it wrong.
 *  The encoded [`CursorPayload`] binds every parameter that could change the
 *  meaning of "the next page".
 */
export type Cursor = string;

/**  Everything the details panel shows for one selected item. */
export type Details = {
	/**  The tree this came from. */
	generation: TreeGeneration,
	/**  The node. */
	node: NodeId,
	/**  Full path, escaped, for display and Copy Path only. */
	path: DisplayPath,
	/**  The escaped display name. */
	name: string,
	/**  Filesystem object kind. */
	kind: Kind,
	/**  Primary content category. */
	category: CategoryId,
	/**  Logical bytes. Shown beside `allocated`, never merged with it. */
	logical: number,
	/**  Allocated bytes. On APFS this is not a reclaimable-space promise. */
	allocated: number,
	/**  Modification time in Unix seconds. */
	mtime: number,
	/**  Bits from [`flags`](crate::flags). */
	flags: number,
	/**  Subtree aggregates, present only for a directory or a virtual group. */
	subtree: DirTotals | null,
	/**
	 *  For a repeated hard link, the path whose traversal counted the bytes.
	 *  The UI says "counted at <path>" rather than implying either path owns
	 *  them physically.
	 */
	counted_at: DisplayPath | null,
	/**  Whether macOS presents this directory as a package. */
	is_package: boolean,
};

/**
 *  Aggregated data for one directory.
 * 
 *  Exactly 56 bytes; with the 4-byte [`NodeId`] beside it that is 60 bytes per
 *  directory, which is the 0.15 GiB line in the memory budget at the 69M/4%
 *  profile. Adding a field here is a budget change, not a detail.
 * 
 *  Counts are `u32`: the design profile is 69M entries and the arena ceiling is
 *  `2^31 - 1` nodes, so a `u64` would buy nothing but 16 more bytes per
 *  directory. Every accumulator saturates rather than wrapping.
 * 
 *  **Logical and allocated stay separate here and everywhere.** They answer
 *  different questions and APFS makes them genuinely disagree; nothing in this
 *  crate adds one to the other or reconciles them.
 */
export type DirTotals = {
	/**  Logical bytes in this subtree, after hard-link policy. */
	logical: number,
	/**  Allocated bytes in this subtree, after hard-link policy. */
	allocated: number,
	/**
	 *  Logical bytes of the files *directly* in this directory. Feeds the
	 *  virtual `<Files>` group, which is a view, not an arena node.
	 */
	direct_logical: number,
	/**  Allocated bytes of the files directly in this directory. */
	direct_allocated: number,
	/**
	 *  Newest modification time anywhere in this subtree, in Unix seconds.
	 *  [`i64::MIN`] means "nothing observed".
	 */
	latest_mtime: number,
	/**
	 *  Entries observed in this subtree, including entries that aggregation
	 *  omitted. Compared against `retained_nodes`, this is what stops an
	 *  aggregated scan from looking like a complete inventory.
	 */
	observed_entries: number,
	/**  Nodes actually retained in this subtree. */
	retained_nodes: number,
	/**  Files directly in this directory, for the virtual group's row count. */
	direct_files: number,
	/**  Directories in this subtree that could not be read. */
	unreadable: number,
};

/**
 *  A path rendered for display, never for a filesystem operation.
 * 
 *  Filesystem names are bytes. This is the escaped, human-readable projection
 *  of those bytes and it is **not action authority**: Reveal and Trash
 *  reconstruct the path from the recorded scan root plus stored components and
 *  then revalidate identity. A path that arrived from JavaScript is never used
 *  to touch the disk (docs/03-MACOS.md#names-case-and-paths).
 * 
 *  # Encoding
 * 
 *  Total and reversible:
 * 
 *  - a literal `%` becomes `%25`;
 *  - any byte that is not part of a valid UTF-8 sequence becomes `%XX`, upper
 *    hex;
 *  - everything else is copied verbatim, in the filesystem's own byte order and
 *    its own Unicode normalization. NFC normalization happens later, for
 *    matching and rendering only.
 */
export type DisplayPath = string;

/**
 *  A stable, coarse classification of an OS error.
 * 
 *  Stable across macOS releases and across the raw `errno` values, so error
 *  counts remain comparable between scans and the UI can key guidance off the
 *  class rather than off a number.
 */
export type ErrorClass = 
/**
 *  `EACCES` or `EPERM`. The only class that may prompt Full Disk Access
 *  guidance.
 */
"permission_denied" | 
/**  `ENOENT`. Usually a race, not a fault. */
"not_found" | 
/**  `ENOTDIR`, or a kind recheck that disagreed with enumeration. */
"not_a_directory" | 
/**  `ELOOP`, or a symlink cycle the traversal refused to follow. */
"symlink_loop" | 
/**  `EMFILE` or `ENFILE`. */
"too_many_open_files" | 
/**  `ENAMETOOLONG`, or a name that exceeded the arena's 16-bit length field. */
"name_too_long" | 
/**
 *  The name is not valid UTF-8, or contains a byte the display layer must
 *  escape. The bytes are still retained losslessly.
 */
"invalid_name" | 
/**  `EIO` and other hardware or filesystem failures. */
"input_output" | 
/**  `ETIMEDOUT`, `EHOSTDOWN`, and other network-filesystem failures. */
"remote_unavailable" | 
/**  Anything else. The raw OS code travels alongside. */
"other";

/**
 *  An uncapped count of errors sharing a class and operation.
 * 
 *  Kept alongside the capped detail list so a summary stays exact even when
 *  the detail list is truncated.
 */
export type ErrorClassCount = {
	/**  The stable class. */
	class: ErrorClass,
	/**  The operation, or `None` for classes that have none. */
	operation: Operation | null,
	/**  How many errors of this class and operation occurred, uncapped. */
	count: number,
};

/**
 *  One exclusion or inclusion rule.
 * 
 *  Rules are compiled once, ordered, and **first match wins**.
 */
export type ExclusionRule = {
	/**  Whether a match is kept or skipped. */
	action: RuleAction,
	/**  What the pattern is matched against. */
	scope: RuleScope,
	/**  The pattern language. */
	syntax: RuleSyntax,
	/**  The pattern itself. */
	pattern: string,
	/**
	 *  Whether matching is case sensitive. APFS can be configured either way,
	 *  so this is never assumed.
	 */
	case_sensitive: boolean,
};

/**
 *  What kind of filesystem object a node is.
 * 
 *  Stored as [`Node::kind`], a `u8`. `#[non_exhaustive]` because filesystem
 *  facts grow: a variant added here must not break a `match` in a sibling
 *  crate.
 * 
 *  Special kinds (socket, device, FIFO) are leaves with zero data contribution
 *  unless platform metadata says otherwise, and their contents are never opened
 *  (docs/02-SCANNER.md#traversal-rules).
 */
export type Kind = 
/**  Anything the reader could not classify, including a metadata failure. */
"unknown" | 
/**  A regular file. */
"file" | 
/**  A directory. Only directories appear in the [`DirIndex`](crate::DirIndex). */
"directory" | 
/**  A symbolic link. Always a leaf: the scanner never follows one. */
"symlink" | 
/**  A Unix domain socket. */
"socket" | 
/**  A named pipe. */
"fifo" | 
/**  A character device. */
"char_device" | 
/**  A block device. */
"block_device";

/**
 *  Which hierarchy layout `layout` should compute.
 * 
 *  All three come from one traversal in `rdirstat-treemap` and share one Arrow
 *  response, but each still owns its geometry, hit testing, labels, and
 *  acceptance gate. A shared buffer does not make the sunburst free.
 */
export type LayoutKind = 
/**  Squarified rectangles. Best for "what is the single biggest thing". */
"treemap" | 
/**
 *  Stacked horizontal bars with depth on the y-axis. Best for "which deep
 *  path is heavy".
 */
"icicle" | 
/**
 *  The icicle in polar coordinates. The best overview and the worst
 *  drill-down: outer rings lose angular resolution.
 */
"sunburst";

/**
 *  Index of a node in the arena, or the sentinel [`NodeId::NONE`], or a tagged
 *  virtual direct-files group.
 * 
 *  The encoding is total and has exactly three disjoint cases:
 * 
 *  | Raw value                        | Meaning                                  |
 *  | -------------------------------- | ---------------------------------------- |
 *  | `0 ..= MAX_NODE_INDEX`           | arena slot                               |
 *  | `NodeId::NONE` (`0x7FFF_FFFF`)   | absent link — no parent, no child        |
 *  | `VIRTUAL_GROUP_BIT \| dir_index` | the `<Files>` group owned by `dir_index` |
 * 
 *  `NONE` is a sentinel rather than `Option<NodeId>` because an `Option` would
 *  double the field width and break the 48-byte [`Node`](crate::Node) budget.
 * 
 *  `0xFFFF_FFFF` is reserved: it would tag the group of the sentinel, which is
 *  not a directory. [`NodeId::is_valid`] rejects it.
 */
export type NodeId = number;

/**
 *  What the scanner or an action was doing when something failed.
 * 
 *  Recorded per error because macOS privacy guidance depends on it: a failure
 *  to `open` a protected directory means something different from a failure to
 *  `stat` an entry that vanished.
 */
export type Operation = 
/**  Opening a directory handle. */
"open_dir" | 
/**  Enumerating directory entries. */
"read_dir" | 
/**  Reading entry metadata. */
"metadata" | 
/**  Reading a symlink target. */
"read_link" | 
/**  Reading volume capacity or identity. */
"stat_fs" | 
/**  Reading file contents, for hashing only. */
"read_file" | 
/**  Revealing an item in Finder. */
"reveal" | 
/**  Moving an item to Trash. */
"trash" | 
/**  Writing or reading a snapshot or catalog artifact. */
"persist";

/**
 *  A read-only query against a published tree failed.
 * 
 *  Every variant is the frontend's cue to do something specific: refetch under
 *  the current generation, clear a selection, or surface a corruption alert.
 */
export type QueryError = 
/**  No completed scan is loaded. */
{ kind: "no_scan" } | 
/**
 *  The request named a generation that is no longer current. The frontend
 *  refetches with `current` rather than mixing two trees.
 */
{ kind: "stale_generation"; detail: {
	/**  What the caller asked for. */
	requested: TreeGeneration,
	/**  What is actually published. */
	current: TreeGeneration,
} } | 
/**  The id does not name a live node in this tree. */
{ kind: "unknown_node"; detail: {
	/**  The offending id. */
	node: NodeId,
} } | 
/**
 *  The operation is not defined on a virtual `<Files>` group. A group has
 *  no path, no children, and no identity to revalidate.
 */
{ kind: "virtual_group"; detail: {
	/**  The offending id. */
	node: NodeId,
} } | 
/**
 *  The cursor is malformed, or was minted for a different generation,
 *  parent, sort key, or direction.
 */
{ kind: "invalid_cursor" } | 
/**
 *  The caller asked for more rows than the hard ceiling
 *  ([`MAX_CHILD_PAGE`](crate::MAX_CHILD_PAGE)).
 */
{ kind: "limit_exceeded"; detail: {
	/**  What the caller asked for. */
	requested: number,
	/**  The ceiling. */
	max: number,
} } | 
/**
 *  A parent chain exceeded [`MAX_TREE_DEPTH`](crate::MAX_TREE_DEPTH) while
 *  reconstructing a path. Fails closed rather than looping.
 */
{ kind: "path_too_deep"; detail: {
	/**  Where the walk started. */
	node: NodeId,
	/**  The depth ceiling. */
	limit: number,
} } | 
/**
 *  The tree failed a structural invariant — a name range outside the blob,
 *  a dangling link. Only reachable from a corrupt snapshot.
 */
{ kind: "corrupt"; detail: ArenaError } | 
/**  The requested report needs a completed catalog scan and there is none. */
{ kind: "no_catalog_scan" } | 
/**  Anything unexpected, already logged with its full source chain. */
{ kind: "internal"; detail: string };

/**
 *  A relocation-specific failure.
 * 
 *  Path-identity failures reuse [`ActionError`] through
 *  [`RelocateError::Action`] rather than being restated here, so the "the thing
 *  you selected is not the thing on disk" rules stay in one place.
 *  `Display` and `Error` are written out by hand rather than derived: `src-tauri`
 *  deliberately does not depend on `thiserror` (docs/08-RUST-PRACTICES.md
 *  reserves it for the library crates and gives the shell `anyhow`), and adding
 *  it for one enum would be the wrong end of that trade.
 */
export type RelocateError = 
/**  A path-identity failure, reused from the Trash path. */
{ kind: "action"; detail: ActionError } | 
/**  The path is one the system needs where it is. */
{ kind: "blocked"; detail: {
	path: DisplayPath,
	reason: string,
} } | 
/**
 *  The destination exists when it must not, or is missing when it must be
 *  there — depending on [`RelocateMode`].
 */
{ kind: "destination"; detail: {
	path: DisplayPath,
	reason: string,
} } | 
/**  Source and destination overlap; copying would recurse. */
{ kind: "overlapping"; detail: {
	source: DisplayPath,
	destination: DisplayPath,
} } | 
/**  The destination filesystem does not have room. */
{ kind: "not_enough_space"; detail: {
	needed: number,
	available: number,
} } | 
/**  `ditto` exited non-zero. */
{ kind: "copy_failed"; detail: string } | 
/**  The copy did not match the source. The source has NOT been touched. */
{ kind: "verify_failed"; detail: {
	path: DisplayPath,
	reason: string,
} } | 
/**
 *  The copy verified, but the symlink could not be created. The source has
 *  already been disposed of — recover it from the Trash. Reported loudly.
 */
{ kind: "symlink_failed"; detail: {
	path: DisplayPath,
	reason: string,
} } | { kind: "internal"; detail: string };

/**  How the destination is reached. */
export type RelocateMode = 
/**
 *  Copy the subtree to a destination that does not exist yet, verify it,
 *  dispose of the source, and symlink. The ordinary case.
 */
"migrate" | 
/**
 *  The destination **already holds** the data — a previous migration that
 *  was interrupted, or a copy the user made themselves. Verify it against
 *  the source, then dispose and symlink. Copies nothing.
 */
"repoint";

/**  What a relocation would do, and the token that authorizes it. */
export type RelocatePlan = {
	generation: TreeGeneration,
	/**
	 *  `None` when [`RelocatePlan::risk`] is [`RiskTier::Blocked`], or when the
	 *  plan found a condition that makes the relocation impossible. A UI must
	 *  treat a plan without a token as "show the reasons, disable the button".
	 */
	token: ConfirmationToken | null,
	node: NodeId,
	source: DisplayPath,
	destination: DisplayPath,
	mode: RelocateMode,
	disposal: SourceDisposal,
	/**  Subtree size as the scan recorded it. */
	logical: number,
	allocated: number,
	/**  Nodes retained under this one, as the scan recorded them. */
	retained_nodes: number,
	/**
	 *  Directories under this one the scan could not read. Non-zero means the
	 *  recorded size is a floor and the copy may be larger than planned.
	 */
	unreadable: number,
	/**
	 *  `st_dev` of the source and of the destination's parent. Equal devices
	 *  mean the move frees nothing, which is a warning, not an error.
	 */
	source_device: number,
	destination_device: number,
	/**  Bytes free on the destination filesystem, from `df -Pk -Y`. */
	destination_available: number,
	/**
	 *  `apfs`, `exfat`, `smbfs`, … Anything that cannot hold extended
	 *  attributes and ACLs is refused, because `ditto` would drop them
	 *  silently and the content comparison would not notice.
	 */
	destination_filesystem: string,
	risk: RiskTier,
	warnings: RelocateWarning[],
};

/**  What a relocation actually did. */
export type RelocateReport = {
	generation: TreeGeneration,
	node: NodeId,
	source: DisplayPath,
	destination: DisplayPath,
	mode: RelocateMode,
	/**
	 *  What was actually done to the source, which is not always what was
	 *  asked: an unverifiable entry downgrades it to [`SourceDisposal::Keep`].
	 */
	disposal: SourceDisposal,
	/**  Regular files compared byte-for-byte and found identical. */
	files_verified: number,
	/**  Bytes in those files. */
	bytes_verified: number,
	/**
	 *  Sockets, FIFOs and device nodes found in the source. `ditto` does not
	 *  carry these and no copy can, so their presence forces `Keep`.
	 */
	special_files: number,
	/**  Whether the symlink now exists at the source path. */
	symlink_created: boolean,
	/**  Set when the relocation did not complete. The source is untouched. */
	error: RelocateError | null,
};

/**  One thing the user should read before confirming. */
export type RelocateWarning = {
	/**  Stable identifier, so the UI can style or suppress a specific warning. */
	code: string,
	/**  Plain sentence, already written for a human. */
	message: string,
};

/**
 *  The closed set of named reports.
 * 
 *  The frontend cannot submit SQL, paths, globs, identifiers, or pragmas. Each
 *  name maps to one reviewed parameterized query with a pinned Arrow schema
 *  version and a row ceiling.
 */
export type ReportName = 
/**  Bytes and counts per content category. */
"category_totals" | 
/**  Bytes and counts per context tag. */
"context_tag_totals" | 
/**  Log-scale size buckets with p50/p90/p99/p99.9. */
"size_buckets" | 
/**  Year and month totals for the age heatmap. */
"age_months" | 
/**  The largest entries. */
"largest_entries" | 
/**  Old, large, compressible entries. */
"archive_candidates" | 
/**  Exact added/removed/grown/shrunk between two catalog scans. */
"scan_diff" | 
/**  The largest logical and allocated deltas in a diff. */
"biggest_movers" | 
/**  Duplicate candidate clusters ranked by potential recovery. */
"duplicate_clusters";

/**
 *  Bound, typed parameters for a named report.
 * 
 *  `#[non_exhaustive]` because phase 6 will add parameters; a sibling
 *  constructs it with `..ReportParams::default()`.
 */
export type ReportParams = {
	/**  Row ceiling for this call. Clamped to the report's own maximum. */
	limit: number,
	/**  Continuation for a cursor-paged report. */
	cursor: Cursor | null,
	/**  Restrict to one content category. */
	category: CategoryId | null,
	/**  Inclusive lower bound on modification time, Unix seconds. */
	since_unix: number | null,
	/**  Exclusive upper bound on modification time, Unix seconds. */
	until_unix: number | null,
	/**  The second scan, for a diff report. */
	compare_to: CatalogScanId | null,
};

/**  How much care this particular path needs. */
export type RiskTier = 
/**  User data. Proceed on confirmation. */
"ordinary" | 
/**  Allowed, but something about it can break a running system. */
"risky" | 
/**  Refused outright. [`plan`] returns this with `token: None`. */
"blocked";

/**  Include or exclude. */
export type RuleAction = 
/**  Descend into, and retain, matches. Overrides a later exclude. */
"include" | 
/**  Skip matches without opening them. */
"exclude";

/**  What part of a path a rule matches against. */
export type RuleScope = 
/**
 *  One directory name component, so a directory literally named `Caches`
 *  matches without `MyCachesBackup` matching too.
 */
"directory_name" | 
/**  The whole path relative to the scan root. */
"root_relative_path";

/**  The pattern language a rule is written in. */
export type RuleSyntax = 
/**  Shell-style glob. */
"glob" | 
/**
 *  Regular expression. Rejected at configuration load if it is invalid or
 *  pathologically expensive; no regex ever compiles inside the scan loop.
 */
"regex";

/**
 *  Entry and node counts for one scan.
 * 
 *  `observed_entries` and `retained_nodes` are tracked separately so an
 *  aggregated scan cannot look like a complete inventory.
 */
export type ScanCounts = {
	/**  Entries the scanner saw, including ones aggregation omitted. */
	observed_entries: number,
	/**  Nodes actually retained in the arena. */
	retained_nodes: number,
	/**  Directories retained. */
	directories: number,
	/**  Regular files retained. */
	files: number,
	/**  Symlinks retained. Always leaves. */
	symlinks: number,
	/**  Sockets, FIFOs, and devices retained. */
	special: number,
	/**  Directories that could not be read. */
	unreadable_dirs: number,
	/**
	 *  Paths skipped by an exclusion rule, counted separately from unreadable
	 *  ones because they mean something completely different.
	 */
	excluded_paths: number,
	/**  Nodes whose children were folded in by `--aggregate-below`. */
	aggregated_nodes: number,
	/**
	 *  Entries that were a later observation of an already-counted
	 *  `(dev, ino)`.
	 */
	hard_link_repeats: number,
};

/**
 *  One recorded, non-fatal failure during a scan.
 * 
 *  The first [`MAX_DETAILED_ERRORS`](crate::MAX_DETAILED_ERRORS) of these are
 *  stored in full; beyond that only [`ErrorClassCount`] rows grow, so a volume
 *  with ten million unreadable paths cannot exhaust memory through its own
 *  error log.
 */
export type ScanError = 
/**
 *  macOS refused access. The scan continues and marks the node
 *  [`flags::UNREADABLE`](crate::flags::UNREADABLE).
 */
{ kind: "permission_denied"; detail: {
	/**  The path that was refused. */
	path: DisplayPath,
	/**  What was being attempted. */
	operation: Operation,
	/**  Raw `errno`, for the diagnostic report. */
	os_code: number,
} } | 
/**
 *  The entry disappeared between enumeration and metadata. Counted as a
 *  mutation; the namespace changed under the scan.
 */
{ kind: "vanished"; detail: {
	/**  The path that went away. */
	path: DisplayPath,
	/**  What was being attempted. */
	operation: Operation,
} } | 
/**
 *  The entry's name is not valid UTF-8 or contains a path separator. The
 *  bytes are retained; only display and search are affected.
 */
{ kind: "invalid_name"; detail: {
	/**  The escaped rendering of the offending path. */
	path: DisplayPath,
} } | 
/**  Any other OS failure on one path. */
{ kind: "io"; detail: {
	/**  The path that failed. */
	path: DisplayPath,
	/**  What was being attempted. */
	operation: Operation,
	/**  The stable class. */
	class: ErrorClass,
	/**  Raw `errno`. */
	os_code: number,
} } | 
/**
 *  The projected peak resident set crossed the configured limit. The scan
 *  ends here rather than at allocation failure, and the UI offers a retry
 *  with aggregation.
 */
{ kind: "memory_limit"; detail: {
	/**  Projected peak RSS at the current growth rate. */
	projected_bytes: number,
	/**  The configured ceiling. */
	limit_bytes: number,
} } | 
/**  The arena could not accept another node or name. Fatal for the scan. */
{ kind: "arena"; detail: ArenaError } | 
/**
 *  The scan root vanished or changed volume identity. Unlike a descendant
 *  failure, this fails the whole scan: the result would not describe the
 *  thing the user asked about.
 */
{ kind: "root_unavailable"; detail: {
	/**  The requested root. */
	path: DisplayPath,
	/**  Human-readable cause, already classified in `class`. */
	reason: string,
	/**  The stable class. */
	class: ErrorClass,
} };

/**
 *  The recorded failures of a scan, for the "N errors" affordance.
 * 
 *  A scan reports a single error count while it runs and per-class counts when
 *  it finishes, and neither answers the only question a user actually asks:
 *  *what* failed. The scanner already knows — it classifies every failure and
 *  keeps the first [`MAX_DETAILED_ERRORS`](crate::MAX_DETAILED_ERRORS) in full
 *  — so this is that knowledge crossing IPC.
 * 
 *  Bounded like every other payload: [`counts`](Self::counts) has one row per
 *  class and operation, and [`samples`](Self::samples) is capped by the caller
 *  with [`truncated`](Self::truncated) saying so. A scan with ten million
 *  unreadable paths returns the same size of answer as one with three.
 */
export type ScanErrorReport = {
	/**
	 *  Whether these are the counters of a running scan. A live report grows;
	 *  a report for the published tree is final.
	 */
	live: boolean,
	/**
	 *  The tree these errors belong to, or [`TreeGeneration::NONE`] while the
	 *  scan that is recording them has not published one.
	 */
	generation: TreeGeneration,
	/**  Every recorded failure, uncapped, however many samples were returned. */
	total: number,
	/**
	 *  Uncapped counts by class and operation.
	 * 
	 *  While a scan is live the operation is `None`: the running counters are
	 *  per class only, because a fixed array of atomics is what the scan path
	 *  is allowed to write and a per-(class, operation) map is not.
	 */
	counts: ErrorClassCount[],
	/**
	 *  The retained failures, in the order they were recorded, capped by the
	 *  caller's `limit`.
	 */
	samples: ScanError[],
	/**  Whether more failures were recorded than are in `samples`. */
	truncated: boolean,
};

/**
 *  Monotonically increasing identifier for one scan attempt.
 * 
 *  Every scan gets one, including scans that are cancelled or fail. The
 *  frontend ignores progress events whose `ScanId` is not the one it started.
 */
export type ScanId = number;

/**
 *  Everything that changes what a scan observes.
 * 
 *  Persisted with the result and hashed into
 *  [`CompletedScan::exclusion_hash`], so two results are only comparable when
 *  their options are.
 */
export type ScanOptions = {
	/**
	 *  Descend past a device boundary. Off by default; a mount marker is
	 *  retained either way.
	 */
	cross_filesystems: boolean,
	/**
	 *  Count hard-linked content once per volume scan. On by default. Later
	 *  entries stay visible and carry
	 *  [`flags::HARD_LINK_REPEAT`](crate::flags::HARD_LINK_REPEAT).
	 */
	count_hard_links_once: boolean,
	/**  Prepend the shipped conservative root-scan exclusions. */
	apply_default_exclusions: boolean,
	/**
	 *  Omit nodes smaller than this, folding their counts and sizes into the
	 *  parent. `None` (the default) retains full detail. An aggregated result
	 *  is visibly marked, and omitted paths cannot be searched, trashed,
	 *  catalogued, or used in exact per-suffix statistics.
	 */
	aggregate_below_bytes: number | null,
	/**
	 *  Reader worker count. `None` selects the measured default, which is not
	 *  `num_cpus` by reflex: too much concurrency turns a sequential disk
	 *  workload into seek contention.
	 */
	workers: number | null,
	/**
	 *  Peak-RSS ceiling. When the published projection crosses it the scan ends
	 *  with [`ScanError::MemoryLimit`] rather than at allocation failure.
	 */
	memory_limit_bytes: number | null,
	/**  Ordered rules, first match wins. */
	exclusions: ExclusionRule[],
};

/**
 *  One throttled progress snapshot.
 * 
 *  Emitted at most [`PROGRESS_MAX_HZ`](crate::PROGRESS_MAX_HZ) times a second,
 *  carrying **absolute counters** plus a sequence number, so a dropped event
 *  costs nothing and events cannot be applied out of order. Completion is a
 *  state transition returned by the supervisor, never inferred from a missing
 *  progress event.
 * 
 *  `src-tauri` emits this under
 *  [`SCAN_PROGRESS_EVENT`](crate::SCAN_PROGRESS_EVENT). Because no crate under
 *  `crates/*` may depend on `tauri`, the `tauri_specta::Event` derive lives in
 *  `src-tauri` on a newtype wrapper around this type.
 */
export type ScanProgress = {
	/**  Which scan this is about. The frontend drops events from older ids. */
	scan_id: ScanId,
	/**  Monotonic per-scan sequence number. */
	sequence: number,
	/**  Lifecycle state at the moment of the snapshot. */
	state: ScanState,
	/**  Entries observed so far. */
	observed_entries: number,
	/**  Nodes retained so far. */
	retained_nodes: number,
	/**  Directories completed so far. */
	directories: number,
	/**  Logical bytes accumulated so far. */
	logical_bytes: number,
	/**  Allocated bytes accumulated so far. */
	allocated_bytes: number,
	/**  Errors recorded so far, all classes. */
	errors: number,
	/**  Entries that changed under the scan so far. */
	mutations: number,
	/**
	 *  Directories queued but not yet read. Exact, not an approximation:
	 *  termination is decided by this counter, not by a heuristic.
	 */
	pending_dirs: number,
	/**  Occupancy of the bounded result channel, for spotting backpressure. */
	result_queue_depth: number,
	/**  Milliseconds since the scan started. */
	elapsed_ms: number,
	/**
	 *  Best-effort display text for the directory being read. Set through a
	 *  non-blocking lock and skipped under contention, because a `format!` per
	 *  entry in a scan worker is a bug.
	 */
	current_dir: DisplayPath | null,
	/**  Current resident set size in bytes. */
	rss_bytes: number,
	/**
	 *  Projected peak RSS at the current growth rate. Crossing the configured
	 *  limit ends the scan with [`ScanError::MemoryLimit`] and offers a retry.
	 */
	projected_peak_rss_bytes: number,
	/**  Mean retained name length in bytes, for the memory profile. */
	mean_name_bytes: number,
	/**
	 *  Retained directories as a fraction of retained nodes, in basis points.
	 *  An integer, so nothing in the progress path touches a float.
	 */
	directory_ratio_bp: number,
};

/**
 *  [`ScanProgress`] on the wire, under
 *  [`SCAN_PROGRESS_EVENT`](rdirstat_core::SCAN_PROGRESS_EVENT).
 * 
 *  The explicit `event_name` matters: the derive would otherwise kebab-case the
 *  Rust identifier into `scan-progress-event`, and the contract pins the wire
 *  name to `scan:progress`.
 */
export type ScanProgressEvent = ScanProgress;

/**
 *  Where a scan is in its lifecycle.
 * 
 *  ```text
 *  Idle -> Scanning -> Cancelling -> Idle
 *                   -> Finalizing -> Ready
 *                   -> Failed     -> Idle
 *  Ready -> Scanning   (the old completed scan stays visible until the
 *                       replacement is ready)
 *  ```
 * 
 *  "Cancel acknowledged" and "all I/O resources closed" are distinct states,
 *  because no design can promise a hard deadline for an uninterruptible remote
 *  filesystem syscall. The frontend adds its own `Empty` and `Loaded` states;
 *  they are presentation, not scan lifecycle.
 */
export type ScanState = 
/**  Nothing is running. */
"idle" | 
/**  Workers are reading and the builder is linking. */
"scanning" | 
/**  Cancellation was requested; producers are stopping. */
"cancelling" | 
/**
 *  Traversal finished; rollup and validation are running. A partial scan
 *  never reaches this state.
 */
"finalizing" | 
/**  A tree was published and has a [`TreeGeneration`]. */
"ready" | 
/**  The scan ended on a fatal error. Nothing is published. */
"failed";

/**
 *  The application state machine, as one `O(1)` answer.
 * 
 *  There is at most one active scan in v1. An old completed scan stays visible
 *  while a replacement runs, which is why `generation` and `summary` can be
 *  populated at the same time as `state == ScanState::Scanning`.
 */
export type ScanStatus = {
	/**  Where the lifecycle is. */
	state: ScanState,
	/**  The active scan, if one is running. */
	active_scan: ScanId | null,
	/**  The published tree, or [`TreeGeneration::NONE`] if nothing is published. */
	generation: TreeGeneration,
	/**  The published scan's summary, if there is one. */
	summary: ScanSummary | null,
	/**
	 *  The most recent progress snapshot, so a client that just connected does
	 *  not have to wait up to 100 ms for the next event.
	 */
	last_progress: ScanProgress | null,
};

/**
 *  The IPC projection of a [`CompletedScan`]: everything except the tree.
 * 
 *  `O(1)` in node count, which is the rule every command obeys.
 */
export type ScanSummary = {
	/**  The attempt that produced this tree. */
	scan_id: ScanId,
	/**  The published generation. */
	generation: TreeGeneration,
	/**  The arena node for the scan root. */
	root: NodeId,
	/**  The scan root, escaped for display only. */
	root_path: DisplayPath,
	/**  Which volume this is. */
	volume: VolumeId,
	/**  Start time, Unix milliseconds. */
	started_unix_ms: number,
	/**  End time, Unix milliseconds. */
	finished_unix_ms: number,
	/**  The options in force. */
	options: ScanOptions,
	/**  Digest of the effective exclusion rule set. */
	exclusion_hash: ConfigHash,
	/**  Digest of the compiled category configuration. */
	category_config_hash: ConfigHash,
	/**  The build that produced this result. */
	tool_version: string,
	/**  Entry and node counts. */
	counts: ScanCounts,
	/**  Logical and allocated totals. */
	totals: ScanTotals,
	/**  Entries that changed under the scan. */
	mutations: number,
	/**  Uncapped error counts by class. The detail list stays in the backend. */
	error_counts: ErrorClassCount[],
	/**  Roots skipped by an exclusion rule. */
	excluded_roots: DisplayPath[],
	/**  Whether aggregation omitted nodes. */
	aggregated: boolean,
	/**  Whether anything makes these totals a floor. */
	partial: boolean,
};

/**
 *  Tree totals for one scan.
 * 
 *  The two numbers are never summed or reconciled. Volume capacity from macOS
 *  is shown *beside* them, never folded in: clones, snapshots, purgeable space,
 *  exclusions, and concurrent mutation all create legitimate deltas.
 */
export type ScanTotals = {
	/**  Logical bytes over the scan root, after hard-link policy. */
	logical: number,
	/**
	 *  Allocated bytes over the scan root, after hard-link policy. On APFS this
	 *  is not a promise of uniquely reclaimable space.
	 */
	allocated: number,
};

/**
 *  One file inside a band, for the breakdown.
 * 
 *  Carries its resolved path because the whole point of expanding a band is to
 *  find out *which* files are in it; a list of node ids would make the caller
 *  issue one `path_of` per row.
 */
export type SizeBandEntry = {
	/**  The arena node, so a row can be selected or revealed. */
	node: NodeId,
	/**  Full path, escaped for display. */
	path: DisplayPath,
	/**
	 *  Allocated bytes, after hard-link policy. The quantity that placed it in
	 *  this band.
	 */
	allocated: number,
	/**  Logical bytes, after hard-link policy. */
	logical: number,
	/**  Modification time in whole Unix seconds. */
	mtime: number,
	/**  Content category index. */
	category: number,
};

/**
 *  One row of the size-band histogram.
 * 
 *  Carries the edges rather than a rendered label so that both front ends
 *  format them with their own `format_iec`/`format_si`, instead of the backend
 *  shipping display text that then cannot be re-styled or localised.
 */
export type SizeBandRow = {
	/**  Band index, `0` smallest. Stable for a given [`SIZE_BAND_EDGES`]. */
	band: number,
	/**  Inclusive lower edge in bytes; `0` for the smallest band. */
	lower_bytes: number,
	/**  Exclusive upper edge in bytes; `None` for the largest band. */
	upper_bytes: number | null,
	/**  Files in this band. */
	files: number,
	/**  Logical bytes of those files, after hard-link policy. */
	logical: number,
	/**
	 *  Allocated bytes of those files, after hard-link policy. This is the
	 *  quantity band membership is decided on.
	 */
	allocated: number,
};

/**
 *  Sort order for a child page. Ties always break on [`NodeId`], so the order
 *  is total and paging cannot repeat or skip a row.
 */
export type Sort = {
	/**  The column. */
	key: SortKey,
	/**  The direction. */
	direction: SortDirection,
};

/**  Ascending or descending. */
export type SortDirection = 
/**  Smallest or earliest first. */
"ascending" | 
/**
 *  Largest or latest first. The default, because the product question is
 *  "what is biggest".
 */
"descending";

/**
 *  Which column the backend sorts a child page by.
 * 
 *  Rust owns ordering, because a client-side sort would need the whole tree in
 *  JavaScript and the IPC contract forbids that. `TanStack Table` therefore runs
 *  in `manualSorting` mode.
 */
export type SortKey = 
/**
 *  Byte-wise name order. Not locale collation, which is not stable across
 *  OS releases.
 */
"name" | 
/**  Logical bytes. */
"logical" | 
/**  Allocated bytes. */
"allocated" | 
/**  Modification time. */
"mtime" | 
/**  Content category, then name. */
"category" | 
/**  Directories before files, then name. */
"kind";

/**  What happens to the original once the copy is proven. */
export type SourceDisposal = 
/**
 *  `NSFileManager.trashItem`. Recoverable through Finder's "Put Back";
 *  the space is not returned until the Trash is emptied. The default.
 */
"trash" | 
/**  Remove immediately. Returns the space at once and is not undoable. */
"delete" | 
/**
 *  Leave the source in place. Produces a *copy*, not a relocation, and no
 *  symlink is created. Chosen automatically when verification finds
 *  something it could not check.
 */
"keep";

/**  Starting a scan failed before any traversal happened. */
export type StartError = 
/**  There is already an active scan. v1 supports exactly one. */
{ kind: "already_scanning"; detail: {
	/**  The scan that holds the slot. */
	scan_id: ScanId,
} } | 
/**  The requested root does not exist. */
{ kind: "root_not_found"; detail: {
	/**  The requested root. */
	path: DisplayPath,
} } | 
/**  The requested root is not a directory. */
{ kind: "root_not_a_directory"; detail: {
	/**  The requested root. */
	path: DisplayPath,
} } | 
/**
 *  macOS refused to open the root. This is the case that may justify Full
 *  Disk Access guidance.
 */
{ kind: "permission_denied"; detail: {
	/**  The requested root. */
	path: DisplayPath,
	/**  Raw `errno`. */
	os_code: number,
} } | 
/**
 *  An exclusion rule failed to compile, a worker count was zero, or another
 *  option was rejected at load. No regex compiles inside the scan loop, so
 *  this is the only place a bad pattern can surface.
 */
{ kind: "invalid_options"; detail: {
	/**  What was wrong. */
	detail: string,
} } | 
/**  Anything unexpected, already logged with its full source chain. */
{ kind: "internal"; detail: string };

/**  What happened to one item in a Trash request. */
export type TrashItemResult = {
	/**  The selected node. */
	node: NodeId,
	/**  Where it was, for the undo affordance and the log. */
	original: DisplayPath,
	/**  Where it landed, when Foundation reported a resulting URL. */
	trashed_to: DisplayPath | null,
	/**
	 *  Bytes as recorded at scan time. Not re-measured: the point of the
	 *  confirmation is that the user approved *these* numbers.
	 */
	scan_time_logical: number,
	/**  Allocated bytes as recorded at scan time. */
	scan_time_allocated: number,
	/**  Why it stayed put, or `None` on success. */
	error: ActionError | null,
};

/**
 *  What the confirmation sheet shows, plus the token that authorizes the move.
 * 
 *  The selection is normalized first — a descendant whose ancestor is already
 *  moving is dropped, and virtual groups and the scan root are rejected — so
 *  the user confirms the count they will actually get.
 */
export type TrashPreview = {
	/**  The tree the selection was made against. */
	generation: TreeGeneration,
	/**  Fresh token, bound to this generation and this normalized set. */
	token: ConfirmationToken,
	/**  The normalized selection. */
	items: TrashPreviewItem[],
	/**  Sum of scan-time logical bytes. */
	total_logical: number,
	/**
	 *  Sum of scan-time allocated bytes. APFS sharing can make physical
	 *  recovery smaller than this; the sheet says so.
	 */
	total_allocated: number,
	/**  How many selected nodes were dropped because an ancestor is moving. */
	dropped_descendants: number,
	/**  Nodes that cannot be trashed at all — virtual groups and the scan root. */
	rejected: NodeId[],
};

/**  One item in a Trash preview. */
export type TrashPreviewItem = {
	/**  The node that will be moved. */
	node: NodeId,
	/**  Its reconstructed path, escaped for display. */
	path: DisplayPath,
	/**  Logical bytes as recorded at scan time. */
	logical: number,
	/**  Allocated bytes as recorded at scan time. */
	allocated: number,
};

/**
 *  The outcome of a Trash request.
 * 
 *  Items are processed independently. This reports partial success honestly
 *  rather than pretending the batch was atomic.
 */
export type TrashReport = {
	/**  The tree the selection was made against. */
	generation: TreeGeneration,
	/**
	 *  Items after normalization — descendants of a selected ancestor are
	 *  dropped, and virtual groups and the scan root are rejected.
	 */
	requested: number,
	/**  How many reached the Trash. */
	moved: number,
	/**  How many failed. */
	failed: number,
	/**  Per-item outcomes, in the order they were attempted. */
	items: TrashItemResult[],
};

/**
 *  Monotonically increasing identifier for one *published* tree.
 * 
 *  Commands take a generation and reject a stale one rather than applying an
 *  old selection, cursor, or confirmation token to a new tree. A cancelled or
 *  failed scan never produces a generation.
 */
export type TreeGeneration = number;

/**  The canvas region a layout is computed for. */
export type Viewport = {
	/**  CSS pixel width. */
	width: number,
	/**  CSS pixel height. */
	height: number,
	/**  Device pixel ratio, so the sub-pixel cutoff is applied in real pixels. */
	device_pixel_ratio: number,
};

/**
 *  Which volume a scan ran against.
 * 
 *  Recorded so a diff can refuse two scans of different volumes, and so a
 *  re-`stat` before Trash can tell "same path" from "same object".
 */
export type VolumeId = {
	/**  `st_dev` of the scan root at start. */
	device: number,
	/**  Filesystem type as reported by `statfs`, e.g. `apfs`. */
	fs_type: string,
	/**  The volume UUID when macOS supplies one. */
	volume_uuid: string | null,
	/**  The mount point, escaped for display. */
	mount_point: DisplayPath,
	/**  Whether the volume preserves case in names. */
	case_preserving: boolean,
	/**
	 *  Whether the volume distinguishes case in lookups. Never assumed: APFS
	 *  can be configured either way.
	 */
	case_sensitive: boolean,
};

/**
 *  Capacity and identity for one mounted volume, for the launch-screen picker.
 * 
 *  Volume capacity is shown **beside** a scan's tree total, never silently
 *  reconciled into it: clones, snapshots, purgeable space, exclusions,
 *  unreadable data, and concurrent mutation all create legitimate deltas.
 * 
 *  # Capacity on APFS is a container property, not a volume property
 * 
 *  Every APFS volume in one container reports that **container's** size and
 *  free space, so `total_bytes` and `available_bytes` are identical across all
 *  of them and `total_bytes - available_bytes` is the container's usage, not
 *  this volume's. Presenting that difference per volume is how five volumes of
 *  one Mac end up each claiming to have used 968 GB of a 995 GB disk.
 * 
 *  [`used_bytes`](Self::used_bytes) is the per-volume number, and
 *  [`container_id`](Self::container_id) / [`disk_id`](Self::disk_id) say which
 *  volumes are sharing the capacity, so the UI can state the shared numbers
 *  once per container and the private number once per volume.
 */
export type VolumeInfo = {
	/**  Display name, e.g. `Macintosh HD`. */
	name: string,
	/**  Mount point, escaped for display. */
	mount_point: DisplayPath,
	/**  `st_dev` of the mount point. */
	device: number,
	/**  Filesystem type, e.g. `apfs`. */
	fs_type: string,
	/**  Total capacity in bytes. **Container-wide on APFS.** */
	total_bytes: number,
	/**  Ordinary available capacity in bytes. **Container-wide on APFS.** */
	available_bytes: number,
	/**
	 *  Bytes this volume itself occupies, as reported for this mount rather
	 *  than derived from `total - available`. This is the only capacity number
	 *  here that is private to the volume.
	 */
	used_bytes: number,
	/**  The device node backing the mount, e.g. `/dev/disk3s1s1`. */
	device_node: string,
	/**
	 *  The APFS container reference (`disk3`), or the whole disk for a
	 *  non-APFS filesystem (`disk4`). `None` when the topology could not be
	 *  read — grouping then degrades to one group per volume rather than to a
	 *  wrong grouping.
	 */
	container_id: string | null,
	/**  The physical whole disk backing the container, e.g. `disk0`. */
	disk_id: string | null,
	/**  Media name of that physical disk, e.g. `APPLE SSD AP1024Z`. */
	disk_name: string | null,
	/**
	 *  Size of that physical disk in bytes, which is larger than a container:
	 *  it includes the other partitions.
	 */
	disk_size_bytes: number | null,
	/**  Whether the backing disk is on an internal bus. */
	is_internal: boolean,
	/**
	 *  Whether macOS considers this volume part of the OS install rather than
	 *  somewhere a user keeps files (`/System/Volumes/*`, Preboot, VM, …).
	 */
	is_system: boolean,
	/**
	 *  Foundation's "available for important usage", where macOS supplies it.
	 *  It can include purgeable capacity and is labelled as such.
	 */
	important_available_bytes: number | null,
	/**  Whether this is the boot volume. */
	is_root_volume: boolean,
	/**  Whether the volume is on removable media. */
	is_removable: boolean,
	/**
	 *  Whether Time Machine local snapshots are present. v1 reports presence
	 *  only: `tmutil` gives no authoritative byte total to subtract from
	 *  `statfs`, so no acceptance gate depends on "snapshot bytes".
	 */
	has_local_snapshots: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

